name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-22.04', 'windows-latest']
        images: ['hello-world', 'alpine']
        exclude:
          - images: ['alpine']
            os: [windows-latest]
        include:
          - image: ['amd64/alpine']
            os: [ubuntu-latest]
    runs-on: ubuntu-${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
