name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-20.04', 'window-latest']
        images: ['hello-world', 'alpine']
    runs-on: ubuntu-${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
