name: If Condition Example
on:
  push:

env: 
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github_action_nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Docker Info
        run: docker info

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_SECRET }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
      
      - name: Docker Publish
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: docker
    concurrency:
      group: production-deployment
      cancel-in-progress: true
    steps:
      - name: Run Docker Image
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo docker run $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            sleep 6000s
          else
            echo "Not running on push event
          fi