name: Exploring Workflow Filter Triggers
on:
  push:
    branches:
      - master
      - develop
      - '!feature/*'
    branches-ignore:
      - 'v*' # Ignore version branches
      - 'feature/*' # Ignore feature branches
      - 'release/**' # Ignore release branches
  # schedule:
  #   - cron: '0/59 * * * *' # Every day at midnight
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - 'README.md' # Ignore changes to README.md
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello, World! This is a filter trigger example."
  